#ifdef BOARD_AB_SMARTHOUSE_HTA_REG6_12CH
    #define DEVICE_ID "AB-HTA-12CH"
    #define HARDWARE_NAME "AB-HTA-12CH"
    #define DEVICE_NAME "AB-SmartHouse Heating Actuator 12x, 6 TE"

    #define INFO_LED_PIN 11
    #define INFO_LED_PIN_ACTIVE_ON HIGH
    #define PROG_LED_PIN 10
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN 9
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

    #define KNX_UART_TX_PIN 12
    #define KNX_UART_RX_PIN 13
    #define SAVE_INTERRUPT_PIN 0

    #define OPENKNX_HTA_MOT_PWR_PIN 26
    #define OPENKNX_HTA_MOT_PWR_PIN_ACTIVE_ON LOW
    #define OPENKNX_HTA_MOT_HIGH1_PIN 1
    #define OPENKNX_HTA_MOT_HIGH1_PIN_ACTIVE_ON LOW
    #define OPENKNX_HTA_MOT_HIGH2_PIN 2
    #define OPENKNX_HTA_MOT_HIGH2_PIN_ACTIVE_ON LOW
    #define OPENKNX_HTA_MOT_LOW1_PIN 3
    #define OPENKNX_HTA_MOT_LOW1_PIN_ACTIVE_ON HIGH
    #define OPENKNX_HTA_MOT_LOW2_PIN 4
    #define OPENKNX_HTA_MOT_LOW2_PIN_ACTIVE_ON HIGH

    #define OPENKNX_HTA_GPIO_PINS 25, 24, 23, 22, 21, 20, 19, 18, 14, 15, 16, 17
    #define OPENKNX_HTA_GPIO_COUNT 12
    #define OPENKNX_HTA_ONLEVEL HIGH

    #define AB_HTA_I2C_WIRE Wire1
    #define AB_HTA_I2C_SDA 6
    #define AB_HTA_I2C_SCL 7

    #define AB_HTA_OUT_TCA1_ADDR 0x20
    #define AB_HTA_OUT_TCA2_ADDR 0x21
    #define AB_HTA_CUR_INA_ADDR 0x40
#endif