#pragma once

#define MAIN_Version "6d5e101"
#define KNX_Version "2.2.2+f6111d3"
#define MODULE_FileTransferModule_Version "0.1.4+3a96b4e"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 4
#define MODULE_FileTransferModule_ETS 1
#define MODULE_Common_Version "1.7.0+120b73a"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 7
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 23
#define MODULE_LogicModule_Version "3.8.0+55beacc"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 8
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 56
#define MODULE_HeatingActuator_Version "0.1.0+1dddea0"
#define MODULE_HeatingActuator_Version_Major 0
#define MODULE_HeatingActuator_Version_Minor 1
#define MODULE_HeatingActuator_Version_Revision 0
#define MODULE_HeatingActuator_ETS 1
#define MODULE_OneWireModule_Version "2.2.0+5e7cabf"
#define MODULE_OneWireModule_Version_Major 2
#define MODULE_OneWireModule_Version_Minor 2
#define MODULE_OneWireModule_Version_Revision 0
#define MODULE_OneWireModule_ETS 34
#define MODULE_SensorDevices_Version "4.1.0+e0f860e"
#define MODULE_SensorDevices_Version_Major 4
#define MODULE_SensorDevices_Version_Minor 1
#define MODULE_SensorDevices_Version_Revision 0
#define MODULE_SensorDevices_ETS 65
