#pragma once

#define MAIN_Version "e7813f7"
#define KNX_Version "2.1.2+764900e"
#define MODULE_LogicModule_Version "3.5.2+9a1cfe1"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 5
#define MODULE_LogicModule_Version_Revision 2
#define MODULE_LogicModule_ETS 53
#define MODULE_Common_Version "1.2.0+9f24e6e"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 2
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 18
#define MODULE_HeatingActuator_Version "0.1.0+cc2a6d5"
#define MODULE_HeatingActuator_Version_Major 0
#define MODULE_HeatingActuator_Version_Minor 1
#define MODULE_HeatingActuator_Version_Revision 0
#define MODULE_HeatingActuator_ETS 1
#define MODULE_GPIOModule_Version "0.0.0+b95bb8c"
#define MODULE_GPIOModule_Version_Major 0
#define MODULE_GPIOModule_Version_Minor 0
#define MODULE_GPIOModule_Version_Revision 0
#define MODULE_GPIOModule_ETS 0
#define MODULE_FileTransferModule_Version "0.1.0+2669301"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 0
#define MODULE_FileTransferModule_ETS 1
#define MODULE_OneWireModule_Version "2.0.0+1cd834a"
#define MODULE_OneWireModule_Version_Major 2
#define MODULE_OneWireModule_Version_Minor 0
#define MODULE_OneWireModule_Version_Revision 0
#define MODULE_OneWireModule_ETS 32
#define MODULE_SensorDevices_Version "4.0.0+9e48dd8"
#define MODULE_SensorDevices_Version_Major 4
#define MODULE_SensorDevices_Version_Minor 0
#define MODULE_SensorDevices_Version_Revision 0
#define MODULE_SensorDevices_ETS 64
